def selection_sort_brute_force(arr):
    counter=0
    tmp_min=-9999
    tmp_var=-9999
    index=-9999
    while(counter < len(arr)): 
        sel_index = counter
        tmp_min = arr[sel_index]
        tmp_index = sel_index
        for index in range((sel_index+1),len(arr)):
            if arr[index] < tmp_min:
                tmp_min = arr[index]
                tmp_index = index 
        tmp_var = arr[sel_index]
        arr[sel_index]=tmp_min
        arr[tmp_index] = tmp_var
        counter+=1 
    return arr 

print(selection_sort_brute_force([1, 2, 3, 4, 5]))
print(selection_sort_brute_force([3, 1, 2, 4, 5]))
print(selection_sort_brute_force([3, 5, 2, 4, 1]))
print(selection_sort_brute_force([3, 5]))
print(selection_sort_brute_force([3]))

# all the above inputs pass - test inputs generated by me 
# did not time this one 